// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import AppSidebar from "@/components/AppSidebar";
// import Navbar from "@/components/Navbar";
// import { SidebarProvider } from "@/components/ui/sidebar";
// import { cookies } from "next/headers";
// import { auth } from "@/auth";
// import axios from "axios";
// import { ThemeProvider } from "@/components/providers/ThemeProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default async function DashboardLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const cookieStore = await cookies();
//   const session = await auth();

//   let role = null;
//   if (session?.access_token) {
//     const { data } = await axios.get(
//       "https://api.escuelajs.co/api/v1/auth/profile",
//       {
//         headers: { Authorization: `Bearer ${session.access_token}` },
//       }
//     );
//     role = data.role;
//     // console.log("User role:", role);
//   }

//   return (
//         <ThemeProvider
//           attribute="class"
//           defaultTheme="system"
//           enableSystem
//           disableTransitionOnChange
//         >
//           <SidebarProvider defaultOpen>
//             <AppSidebar />
//             <main className="w-full">
//               <Navbar role={role} />
//               <div className="px-4">{children}</div>
//             </main>
//           </SidebarProvider>
//         </ThemeProvider>
//   );
// }


import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "@/components/AppSidebar";
import Navbar from "@/components/Navbar";
import { auth } from "@/auth";
import { redirect } from "next/navigation";

export default async function DashboardLayout({ children }: { children: React.ReactNode }) {
  const session = await auth();

  if (!session) {
    redirect("/login"); // 🔐 proteger rutas
  }

  return (
    <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
      <SidebarProvider defaultOpen>
        <div className="flex w-full h-full">
          <AppSidebar />
          <main className="w-full">
            <Navbar role={session.user?.role} />
            <div className="px-4">{children}</div>
          </main>
        </div>
      </SidebarProvider>
    </ThemeProvider>
  );
}

