// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import AppSidebar from "@/components/AppSidebar";
// import Navbar from "@/components/Navbar";
// import { ThemeProvider } from "@/components/providers/ThemeProvider";
// import { SidebarProvider } from "@/components/ui/sidebar";
// import { cookies } from "next/headers";
// import { auth } from "@/auth";
// import axios from "axios";



// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const cookieStore = await cookies();
//   const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";
//   const session = await auth();

//   let role = null;
//   if (session?.access_token) {
//     const { data } = await axios.get(
//       "https://api.escuelajs.co/api/v1/auth/profile",
//       {
//         headers: { Authorization: `Bearer ${session.access_token}` },
//       }
//     );
//     role = data.role;
//     console.log("User role:", role);
//   }

//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
//       >
//         {" "}
//           <ThemeProvider
//             attribute="class"
//             defaultTheme="system" 
//             enableSystem
//             disableTransitionOnChange 
//           >
//             <SidebarProvider defaultOpen={defaultOpen}>
//               <AppSidebar />
//               <main className="w-full">
//                 <Navbar role={role}/>
//                 <div className="px-4">{children}</div>
//               </main>
//             </SidebarProvider>
//           </ThemeProvider>
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({ subsets: ["latin"], variable: "--font-geist-sans" });
const geistMono = Geist_Mono({ subsets: ["latin"], variable: "--font-geist-mono" });

export const metadata: Metadata = {
  title: "Mi App",
  description: "Dashboard con login",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es" suppressHydrationWarning className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
